// LiteStay - Preload 脚本
const { contextBridge, ipcRenderer } = require('electron');
const { CH } = require('./db-handlers/utils.cjs');

contextBridge.exposeInMainWorld('electron', {
  getPlatform: () => ipcRenderer.invoke('CH.getPlatform'),
  win: {
    minimize: () => ipcRenderer.send('CH.winMinimize'),
    maximize: () => ipcRenderer.send('CH.winMaximize'),
    close: () => ipcRenderer.send('CH.winClose'),
    onMaximized: (callback) => ipcRenderer.on('CH.winMaximized', (_e, val) => callback(val)),
    onOrdersChanged: (callback) => ipcRenderer.on('CH.ordersChanged', () => callback()),
  },
  db: {
    getRoomTypes: () => ipcRenderer.invoke('CH.getRoomTypes'),
    insertRoomType: (name) => ipcRenderer.invoke('CH.insertRoomType', name),
    deleteRoomType: (typeId) => ipcRenderer.invoke('CH.deleteRoomType', typeId),
    insertRoom: (room) => ipcRenderer.invoke('CH.insertRoom', room),
    getRooms: () => ipcRenderer.invoke('CH.getRooms'),
    deleteRoom: (roomId) => ipcRenderer.invoke('CH.deleteRoom', roomId),
    updateRoom: (roomId, updates) => ipcRenderer.invoke('CH.updateRoom', roomId, updates),
    insertOrder: (order) => ipcRenderer.invoke('CH.insertOrder', order),
    getOrders: () => ipcRenderer.invoke('CH.getOrders'),
    updateOrder: (orderId, updates) => ipcRenderer.invoke('CH.updateOrder', orderId, updates),
    deleteOrder: (orderId) => ipcRenderer.invoke('CH.deleteOrder', orderId),
    insertFinancialLog: (log) => ipcRenderer.invoke('CH.insertFinancialLog', log),
    getFinancialLogs: (date) => ipcRenderer.invoke('CH.getFinancialLogs', date),
    getFinancialLogsByOrder: (orderId) => ipcRenderer.invoke('CH.getFinancialLogsByOrder', orderId),
    updateFinancialLogPayment: (orderId, pm) => ipcRenderer.invoke('CH.updateFinancialLogPayment', orderId, pm),
    updateFinancialLogAmount: (orderId, type, amount) => ipcRenderer.invoke('CH.updateFinancialLogAmount', orderId, type, amount),
    deleteFinancialLog: (logId) => ipcRenderer.invoke('CH.deleteFinancialLog', logId),
    updateFinancialLog: (logId, updates) => ipcRenderer.invoke('CH.updateFinancialLog', logId, updates),
    getIncidentalSums: () => ipcRenderer.invoke('CH.getIncidentalSums'),
    getFinancialSummary: (df, dt) => ipcRenderer.invoke('CH.getFinancialSummary', df, dt),
    getFinancialLogsDetailed: (df, dt) => ipcRenderer.invoke('CH.getFinancialLogsDetailed', df, dt),
    getRevenueByRoomType: (df, dt) => ipcRenderer.invoke('CH.getRevenueByRoomType', df, dt),
    getOccupancyStats: (date) => ipcRenderer.invoke('CH.getOccupancyStats', date),
    getDailyOccupancy: (df, dt) => ipcRenderer.invoke('CH.getDailyOccupancy', df, dt),
    getDailyRevenueByType: (df, dt) => ipcRenderer.invoke('CH.getDailyRevenueByType', df, dt),
    getRoomTypeAnalysis: (df, dt) => ipcRenderer.invoke('CH.getRoomTypeAnalysis', df, dt),
    exportFinancialLogs: (df, dt) => ipcRenderer.invoke('CH.exportFinancialLogs', df, dt),
    exportNightAudit: (data) => ipcRenderer.invoke('CH.exportNightAudit', data),
    getGuests: () => ipcRenderer.invoke('CH.getGuests'),
    getGuestById: (id) => ipcRenderer.invoke('CH.getGuestById', id),
    getGuestByPhone: (phone) => ipcRenderer.invoke('CH.getGuestByPhone', phone),
    insertGuest: (guest) => ipcRenderer.invoke('CH.insertGuest', guest),
    updateGuest: (guestId, updates) => ipcRenderer.invoke('CH.updateGuest', guestId, updates),
    deleteGuest: (guestId) => ipcRenderer.invoke('CH.deleteGuest', guestId),
    findOrCreateGuest: (data) => ipcRenderer.invoke('CH.findOrCreateGuest', data),
    getGuestsWithStats: () => ipcRenderer.invoke('CH.getGuestsWithStats'),
    searchGuests: (query) => ipcRenderer.invoke('CH.searchGuests', query),
    getGuestOrders: (name) => ipcRenderer.invoke('CH.getGuestOrders', name),
    getBackups: () => ipcRenderer.invoke('CH.getBackups'),
    createBackup: (name) => ipcRenderer.invoke('CH.createBackup', name),
    restoreBackup: (file) => ipcRenderer.invoke('CH.restoreBackup', file),
    deleteBackup: (file) => ipcRenderer.invoke('CH.deleteBackup', file),
    exportBackup: (file) => ipcRenderer.invoke('CH.exportBackup', file),
    importBackup: () => ipcRenderer.invoke('CH.importBackup'),
    getPriceRules: () => ipcRenderer.invoke('CH.getPriceRules'),
    insertPriceRule: (rule) => ipcRenderer.invoke('CH.insertPriceRule', rule),
    updatePriceRule: (id, updates) => ipcRenderer.invoke('CH.updatePriceRule', id, updates),
    deletePriceRule: (id) => ipcRenderer.invoke('CH.deletePriceRule', id),
    getPriceCalendar: (type, df, dt) => ipcRenderer.invoke('CH.getPriceCalendar', type, df, dt),
    getMonthlyRevenue: (year) => ipcRenderer.invoke('CH.getMonthlyRevenue', year),
    getQuarterlyRevenue: (year) => ipcRenderer.invoke('CH.getQuarterlyRevenue', year),
    getYearlyRevenue: () => ipcRenderer.invoke('CH.getYearlyRevenue'),
    getRevenueGrowth: () => ipcRenderer.invoke('CH.getRevenueGrowth'),
    getPaymentMethodTrend: (months) => ipcRenderer.invoke('CH.getPaymentMethodTrend', months),
    getSourceStats: (df, dt) => ipcRenderer.invoke('CH.getSourceStats', df, dt),
    getSourceTrend: (months) => ipcRenderer.invoke('CH.getSourceTrend', months),
    updateOrderSource: (id, source) => ipcRenderer.invoke('CH.updateOrderSource', id, source),
    getADRRevPAR: (df, dt) => ipcRenderer.invoke('CH.getADRRevPAR', df, dt),
    getADRRevPARTrend: (days) => ipcRenderer.invoke('CH.getADRRevPARTrend', days),
    getADRByRoomType: (df, dt) => ipcRenderer.invoke('CH.getADRByRoomType', df, dt),
    getInvoices: () => ipcRenderer.invoke('CH.getInvoices'),
    insertInvoice: (inv) => ipcRenderer.invoke('CH.insertInvoice', inv),
    updateInvoice: (id, updates) => ipcRenderer.invoke('CH.updateInvoice', id, updates),
    deleteInvoice: (id) => ipcRenderer.invoke('CH.deleteInvoice', id),
    markInvoiceIssued: (id) => ipcRenderer.invoke('CH.markInvoiceIssued', id),
    exportInvoiceList: (status) => ipcRenderer.invoke('CH.exportInvoiceList', status),
  },
  edition: {
    getInfo: () => ipcRenderer.invoke('CH.editionGetInfo'),
    checkTrial: () => ipcRenderer.invoke('CH.editionCheckTrial'),
    activate: (key) => ipcRenderer.invoke('CH.editionActivate', key),
  },
});
