// LiteStay - Preload 脚本
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  getPlatform: () => ipcRenderer.invoke('get:platform'),
  win: {
    minimize: () => ipcRenderer.send('win:minimize'),
    maximize: () => ipcRenderer.send('win:maximize'),
    close: () => ipcRenderer.send('win:close'),
    onMaximized: (callback) => ipcRenderer.on('win:maximized', (_e, val) => callback(val)),
    onOrdersChanged: (callback) => ipcRenderer.on('orders:changed', () => callback()),
  },
  db: {
    getRoomTypes: () => ipcRenderer.invoke('db:getRoomTypes'),
    insertRoomType: (name) => ipcRenderer.invoke('db:insertRoomType', name),
    deleteRoomType: (typeId) => ipcRenderer.invoke('db:deleteRoomType', typeId),
    insertRoom: (room) => ipcRenderer.invoke('db:insertRoom', room),
    getRooms: () => ipcRenderer.invoke('db:getRooms'),
    deleteRoom: (roomId) => ipcRenderer.invoke('db:deleteRoom', roomId),
    updateRoom: (roomId, updates) => ipcRenderer.invoke('db:updateRoom', roomId, updates),
    insertOrder: (order) => ipcRenderer.invoke('db:insertOrder', order),
    getOrders: () => ipcRenderer.invoke('db:getOrders'),
    updateOrder: (orderId, updates) => ipcRenderer.invoke('db:updateOrder', orderId, updates),
    deleteOrder: (orderId) => ipcRenderer.invoke('db:deleteOrder', orderId),
    insertFinancialLog: (log) => ipcRenderer.invoke('db:insertFinancialLog', log),
    getFinancialLogs: (date) => ipcRenderer.invoke('db:getFinancialLogs', date),
    getFinancialLogsByOrder: (orderId) => ipcRenderer.invoke('db:getFinancialLogsByOrder', orderId),
    updateFinancialLogPayment: (orderId, pm) => ipcRenderer.invoke('db:updateFinancialLogPayment', orderId, pm),
    updateFinancialLogAmount: (orderId, type, amount) => ipcRenderer.invoke('db:updateFinancialLogAmount', orderId, type, amount),
    deleteFinancialLog: (logId) => ipcRenderer.invoke('db:deleteFinancialLog', logId),
    updateFinancialLog: (logId, updates) => ipcRenderer.invoke('db:updateFinancialLog', logId, updates),
    getIncidentalSums: () => ipcRenderer.invoke('db:getIncidentalSums'),
    getFinancialSummary: (df, dt) => ipcRenderer.invoke('db:getFinancialSummary', df, dt),
    getFinancialLogsDetailed: (df, dt) => ipcRenderer.invoke('db:getFinancialLogsDetailed', df, dt),
    getRevenueByRoomType: (df, dt) => ipcRenderer.invoke('db:getRevenueByRoomType', df, dt),
    getOccupancyStats: (date) => ipcRenderer.invoke('db:getOccupancyStats', date),
    getDailyOccupancy: (df, dt) => ipcRenderer.invoke('db:getDailyOccupancy', df, dt),
    getDailyRevenueByType: (df, dt) => ipcRenderer.invoke('db:getDailyRevenueByType', df, dt),
    getRoomTypeAnalysis: (df, dt) => ipcRenderer.invoke('db:getRoomTypeAnalysis', df, dt),
    exportFinancialLogs: (df, dt) => ipcRenderer.invoke('db:exportFinancialLogs', df, dt),
    exportNightAudit: (data) => ipcRenderer.invoke('db:exportNightAudit', data),
    getGuests: () => ipcRenderer.invoke('db:getGuests'),
    getGuestById: (id) => ipcRenderer.invoke('db:getGuestById', id),
    getGuestByPhone: (phone) => ipcRenderer.invoke('db:getGuestByPhone', phone),
    insertGuest: (guest) => ipcRenderer.invoke('db:insertGuest', guest),
    updateGuest: (guestId, updates) => ipcRenderer.invoke('db:updateGuest', guestId, updates),
    deleteGuest: (guestId) => ipcRenderer.invoke('db:deleteGuest', guestId),
    findOrCreateGuest: (data) => ipcRenderer.invoke('db:findOrCreateGuest', data),
    getGuestsWithStats: () => ipcRenderer.invoke('db:getGuestsWithStats'),
    searchGuests: (query) => ipcRenderer.invoke('db:searchGuests', query),
    getGuestOrders: (name) => ipcRenderer.invoke('db:getGuestOrders', name),
    getBackups: () => ipcRenderer.invoke('db:getBackups'),
    createBackup: (name) => ipcRenderer.invoke('db:createBackup', name),
    restoreBackup: (file) => ipcRenderer.invoke('db:restoreBackup', file),
    deleteBackup: (file) => ipcRenderer.invoke('db:deleteBackup', file),
    exportBackup: (file) => ipcRenderer.invoke('db:exportBackup', file),
    importBackup: () => ipcRenderer.invoke('db:importBackup'),
    getPriceRules: () => ipcRenderer.invoke('db:getPriceRules'),
    insertPriceRule: (rule) => ipcRenderer.invoke('db:insertPriceRule', rule),
    updatePriceRule: (id, updates) => ipcRenderer.invoke('db:updatePriceRule', id, updates),
    deletePriceRule: (id) => ipcRenderer.invoke('db:deletePriceRule', id),
    getPriceCalendar: (type, df, dt) => ipcRenderer.invoke('db:getPriceCalendar', type, df, dt),
    getMonthlyRevenue: (year) => ipcRenderer.invoke('db:getMonthlyRevenue', year),
    getQuarterlyRevenue: (year) => ipcRenderer.invoke('db:getQuarterlyRevenue', year),
    getYearlyRevenue: () => ipcRenderer.invoke('db:getYearlyRevenue'),
    getRevenueGrowth: () => ipcRenderer.invoke('db:getRevenueGrowth'),
    getPaymentMethodTrend: (months) => ipcRenderer.invoke('db:getPaymentMethodTrend', months),
    getSourceStats: (df, dt) => ipcRenderer.invoke('db:getSourceStats', df, dt),
    getSourceTrend: (months) => ipcRenderer.invoke('db:getSourceTrend', months),
    updateOrderSource: (id, source) => ipcRenderer.invoke('db:updateOrderSource', id, source),
    getADRRevPAR: (df, dt) => ipcRenderer.invoke('db:getADRRevPAR', df, dt),
    getADRRevPARTrend: (days) => ipcRenderer.invoke('db:getADRRevPARTrend', days),
    getADRByRoomType: (df, dt) => ipcRenderer.invoke('db:getADRByRoomType', df, dt),
    getInvoices: () => ipcRenderer.invoke('db:getInvoices'),
    insertInvoice: (inv) => ipcRenderer.invoke('db:insertInvoice', inv),
    updateInvoice: (id, updates) => ipcRenderer.invoke('db:updateInvoice', id, updates),
    deleteInvoice: (id) => ipcRenderer.invoke('db:deleteInvoice', id),
    markInvoiceIssued: (id) => ipcRenderer.invoke('db:markInvoiceIssued', id),
    exportInvoiceList: (status) => ipcRenderer.invoke('db:exportInvoiceList', status),
  },
  edition: {
    getInfo: () => ipcRenderer.invoke('edition:get-info'),
    checkTrial: () => ipcRenderer.invoke('edition:check-trial'),
    activate: (key) => ipcRenderer.invoke('edition:activate', key),
  },
});
