// LiteStay - Preload 脚本
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  getPlatform: () => ipcRenderer.invoke('get:platform'),
  win: {
    minimize: () => ipcRenderer.send('win:minimize'),
    maximize: () => ipcRenderer.send('win:maximize'),
    close: () => ipcRenderer.send('win:close'),
    onMaximized: (callback) => ipcRenderer.on('win:maximized', (_e, val) => callback(val)),
    onOrdersChanged: (callback) => ipcRenderer.on('orders:changed', () => callback()),
  },
  db: {
    getRoomTypes: () => ipcRenderer.invoke('db:getRoomTypes'),
    insertRoomType: (name) => ipcRenderer.invoke('db:insertRoomType', name),
    deleteRoomType: (typeId) => ipcRenderer.invoke('db:deleteRoomType', typeId),
    insertRoom: (room) => ipcRenderer.invoke('db:insertRoom', room),
    getRooms: () => ipcRenderer.invoke('db:getRooms'),
    deleteRoom: (roomId) => ipcRenderer.invoke('db:deleteRoom', roomId),
    updateRoom: (roomId, updates) => ipcRenderer.invoke('db:updateRoom', roomId, updates),
    insertOrder: (order) => ipcRenderer.invoke('db:insertOrder', order),
    getOrders: () => ipcRenderer.invoke('db:getOrders'),
    updateOrder: (orderId, updates) => ipcRenderer.invoke('db:updateOrder', orderId, updates),
    deleteOrder: (orderId) => ipcRenderer.invoke('db:deleteOrder', orderId),
    insertFinancialLog: (log) => ipcRenderer.invoke('db:insertFinancialLog', log),
    getFinancialLogs: (date) => ipcRenderer.invoke('db:getFinancialLogs', date),
    getFinancialLogsByOrder: (orderId) => ipcRenderer.invoke('db:getFinancialLogsByOrder', orderId),
    updateFinancialLogPayment: (orderId, paymentMethod) => ipcRenderer.invoke('db:updateFinancialLogPayment', orderId, paymentMethod),
    updateFinancialLogAmount: (orderId, type, amount) => ipcRenderer.invoke('db:updateFinancialLogAmount', orderId, type, amount),
    deleteFinancialLog: (logId) => ipcRenderer.invoke('db:deleteFinancialLog', logId),
    updateFinancialLog: (logId, updates) => ipcRenderer.invoke('db:updateFinancialLog', logId, updates),
    getIncidentalSums: () => ipcRenderer.invoke('db:getIncidentalSums'),
    getFinancialSummary: (dateFrom, dateTo) => ipcRenderer.invoke('db:getFinancialSummary', dateFrom, dateTo),
    getFinancialLogsDetailed: (dateFrom, dateTo) => ipcRenderer.invoke('db:getFinancialLogsDetailed', dateFrom, dateTo),
    getRevenueByRoomType: (dateFrom, dateTo) => ipcRenderer.invoke('db:getRevenueByRoomType', dateFrom, dateTo),
    getOccupancyStats: (date) => ipcRenderer.invoke('db:getOccupancyStats', date),
    getDailyOccupancy: (dateFrom, dateTo) => ipcRenderer.invoke('db:getDailyOccupancy', dateFrom, dateTo),
    getDailyRevenueByType: (dateFrom, dateTo) => ipcRenderer.invoke('db:getDailyRevenueByType', dateFrom, dateTo),
    getRoomTypeAnalysis: (dateFrom, dateTo) => ipcRenderer.invoke('db:getRoomTypeAnalysis', dateFrom, dateTo),
    exportFinancialLogs: (dateFrom, dateTo) => ipcRenderer.invoke('db:exportFinancialLogs', dateFrom, dateTo),
    exportNightAudit: (auditData) => ipcRenderer.invoke('db:exportNightAudit', auditData),
    getGuests: () => ipcRenderer.invoke('db:getGuests'),
    getGuestById: (guestId) => ipcRenderer.invoke('db:getGuestById', guestId),
    getGuestByPhone: (phone) => ipcRenderer.invoke('db:getGuestByPhone', phone),
    insertGuest: (guest) => ipcRenderer.invoke('db:insertGuest', guest),
    updateGuest: (guestId, updates) => ipcRenderer.invoke('db:updateGuest', guestId, updates),
    deleteGuest: (guestId) => ipcRenderer.invoke('db:deleteGuest', guestId),
    findOrCreateGuest: (guestData) => ipcRenderer.invoke('db:findOrCreateGuest', guestData),
    getGuestsWithStats: () => ipcRenderer.invoke('db:getGuestsWithStats'),
    searchGuests: (query) => ipcRenderer.invoke('db:searchGuests', query),
    getGuestOrders: (guestName) => ipcRenderer.invoke('db:getGuestOrders', guestName),
    getBackups: () => ipcRenderer.invoke('db:getBackups'),
    createBackup: (customName) => ipcRenderer.invoke('db:createBackup', customName),
    restoreBackup: (backupFilename) => ipcRenderer.invoke('db:restoreBackup', backupFilename),
    deleteBackup: (backupFilename) => ipcRenderer.invoke('db:deleteBackup', backupFilename),
    exportBackup: (backupFilename) => ipcRenderer.invoke('db:exportBackup', backupFilename),
    importBackup: () => ipcRenderer.invoke('db:importBackup'),
    getPriceRules: () => ipcRenderer.invoke('db:getPriceRules'),
    insertPriceRule: (rule) => ipcRenderer.invoke('db:insertPriceRule', rule),
    updatePriceRule: (ruleId, updates) => ipcRenderer.invoke('db:updatePriceRule', ruleId, updates),
    deletePriceRule: (ruleId) => ipcRenderer.invoke('db:deletePriceRule', ruleId),
    getPriceCalendar: (roomType, dateFrom, dateTo) => ipcRenderer.invoke('db:getPriceCalendar', roomType, dateFrom, dateTo),
    getMonthlyRevenue: (year) => ipcRenderer.invoke('db:getMonthlyRevenue', year),
    getQuarterlyRevenue: (year) => ipcRenderer.invoke('db:getQuarterlyRevenue', year),
    getYearlyRevenue: () => ipcRenderer.invoke('db:getYearlyRevenue'),
    getRevenueGrowth: () => ipcRenderer.invoke('db:getRevenueGrowth'),
    getPaymentMethodTrend: (months) => ipcRenderer.invoke('db:getPaymentMethodTrend', months),
    getSourceStats: (dateFrom, dateTo) => ipcRenderer.invoke('db:getSourceStats', dateFrom, dateTo),
    getSourceTrend: (months) => ipcRenderer.invoke('db:getSourceTrend', months),
    updateOrderSource: (orderId, source) => ipcRenderer.invoke('db:updateOrderSource', orderId, source),
    getADRRevPAR: (dateFrom, dateTo) => ipcRenderer.invoke('db:getADRRevPAR', dateFrom, dateTo),
    getADRRevPARTrend: (days) => ipcRenderer.invoke('db:getADRRevPARTrend', days),
    getADRByRoomType: (dateFrom, dateTo) => ipcRenderer.invoke('db:getADRByRoomType', dateFrom, dateTo),
    getInvoices: () => ipcRenderer.invoke('db:getInvoices'),
    insertInvoice: (invoice) => ipcRenderer.invoke('db:insertInvoice', invoice),
    updateInvoice: (invoiceId, updates) => ipcRenderer.invoke('db:updateInvoice', invoiceId, updates),
    deleteInvoice: (invoiceId) => ipcRenderer.invoke('db:deleteInvoice', invoiceId),
    markInvoiceIssued: (invoiceId) => ipcRenderer.invoke('db:markInvoiceIssued', invoiceId),
    exportInvoiceList: (status) => ipcRenderer.invoke('db:exportInvoiceList', status),
  },
  edition: {
    getInfo: () => ipcRenderer.invoke('edition:get-info'),
    checkTrial: () => ipcRenderer.invoke('edition:check-trial'),
    activate: (licenseKey) => ipcRenderer.invoke('edition:activate', licenseKey),
  },
});
