// Barrel file — re-exports all domain types
export type { RoomType, Room } from './types/room'
export type { Order, GuestOrder } from './types/order'
export { SOURCE_LABELS } from './types/order'
export type { FinancialLog, FinancialLogDetailed, FinancialSummary, RevenueByRoomType, OccupancyStats, NightAuditData } from './types/finance'
export type { DailyOccupancy, DailyRevenueByType, RoomTypeAnalysis, MonthlyRevenue, QuarterlyRevenue, YearlyRevenue, RevenueGrowth, PaymentMethodTrend, SourceStat, SourceTrend, ADRRevPARData, ADRRevPARTrend, ADRByRoomType } from './types/analytics'
export type { PriceRule, PriceCalendar } from './types/pricing'
export type { Guest, GuestWithStats } from './types/guest'
export type { Invoice, InvoiceWithOrder } from './types/invoice'
export type { BackupInfo } from './types/backup'
export type { ElectronAPI } from './types/electron'
export type { Edition, EditionInfo } from './editions'
